name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/96573011708/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: github-actions-service-account@my-project-1540367072726.iam.gserviceaccount.com

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: gridly-slack-bot
          runtime: nodejs20
          memory_mb: 128
          region: europe-west3
          entry_point: app
          https_trigger_security_level: secure_always
          env_vars: |
            TZ=${{ secrets.TZ }}
            SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}
            SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}
            GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_REFRESH_TOKEN=${{ secrets.GOOGLE_REFRESH_TOKEN }}
            SERVICE_ACCOUNT_KEY_BASE64=${{ secrets.SERVICE_ACCOUNT_KEY_BASE64 }}
